###
POST http://localhost:9091/api/signup HTTP/1.1
Content-Type: application/json

{
    "email": "o.ohmry@gmail.com",
    "password": "oohmry",
    "name": "이병훈"
}

###
POST http://localhost:9091/api/signin HTTP/1.1
Content-Type: application/json

{
    "email": "o.ohmry@gmail.com",
    "password": "oohmry"
}

###
PUT http://localhost:9091/api/user HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTY0ODM0ODUsImV4cCI6MTY1NjQ4NTI4NSwidXNlcklkIjoxLCJlbWFpbCI6Im8ub2htcnlAZ21haWwuY29tIiwiY2xpZW50SXAiOiIxMjcuMC4wLjEiLCJyb2xlcyI6WyJVU0VSIl19.09fw4hysybMkZq9bFq5zb2i8mfAXpSW2PjJa-AY6Edc
Content-Type: application/json

{
    "id": 1,
    "name": "이병훈_수정",
    "role": "ADMIN"
}

###
GET http://localhost:9091/api/user?pageNo=0&recordCount=20 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTY0ODM1OTQsImV4cCI6MTY1NjQ4NTM5NCwidXNlcklkIjoxLCJlbWFpbCI6Im8ub2htcnlAZ21haWwuY29tIiwiY2xpZW50SXAiOiIxMjcuMC4wLjEiLCJyb2xlcyI6WyJBRE1JTiJdfQ.jFsqlUFOw43MLYrx2e_RKdsURNsUOcUlRxewMKK3qug