###
POST http://localhost:9091/api/signup HTTP/1.1
Content-Type: application/json

{
  "id": null,
  "name": "이병훈",
  "email": "o.ohmry@gmail.com",
  "password": "oohmry"
}

###
POST http://localhost:9091/api/signin HTTP/1.1
Content-Type: application/json

{
  "email": "o.ohmry@gmail.com",
  "password": "oohmry"
}

###
POST http://localhost:9091/api/resign HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTYyNTIzMTksImV4cCI6MTY1NjI1NDExOSwicHJpbmNpcGFsIjoiby5vaG1yeUBnbWFpbC5jb20ifQ.BBE7fA4LUS2rEL3msIJHK8T4ArlYYWtfSLulK1tC7Kw

{
  "refreshToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTYyNTIzMTksImV4cCI6MTY1NjI5NTUxOSwicHJpbmNpcGFsIjoiby5vaG1yeUBnbWFpbC5jb20ifQ.0EtdPHOTRFb1UQwMNv1Hkawteer5h1uZcFkBTs6SyUw"
}


###
GET http://localhost:9091/api/user/1 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTYyNTIzMTksImV4cCI6MTY1NjI1NDExOSwicHJpbmNpcGFsIjoiby5vaG1yeUBnbWFpbC5jb20ifQ.BBE7fA4LUS2rEL3msIJHK8T4ArlYYWtfSLulK1tC7Kw

###
GET http://localhost:9091/api/user HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTYyNTIzMzcsImV4cCI6MTY1NjI1NDEzNywicHJpbmNpcGFsIjoiby5vaG1yeUBnbWFpbC5jb20ifQ.Dv6rJv1KNxMUsdOaE7AEDBfxzm0N7hmKobs8ReXX9W0

###
PUT http://localhost:9091/api/user/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvLm9obXJ5QGdtYWlsLmNvbSIsImlhdCI6MTY1NjI0NDcyNCwiZXhwIjoxNjU2MjQ2NTI0fQ.D708t5vjCo6axIGmXeB9Y2gbYFURvGgDSjgO_1Xm1jw

{
  "id": 1,
  "name": "이병훈_수정"
}

###
PUT http://localhost:9091/api/user/1/credential HTTP/1.1
Content-Type: application/json

{
  "id": 1,
  "password": "oohmry",
  "newPassword": "oohmry2"
}