server:
  port: 9091
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    format-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect