server:
  port: 9091
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    database-platform: org.hibernate.dialect.OracleDialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.OracleDialect